name: CI - Integration Tests

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  integration:
    name: Run Integration Tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Setup yt-dlp + ffmpeg
        uses: AnimMouse/setup-yt-dlp@v3
        with:
          ffmpeg: true

      - name: Check yt-dlp Version
        run: yt-dlp --version

      - name: Run Integration Tests
        env:
          YTDLP_INTEGRATION_TESTS: "1"
        run: dotnet test tests/Ytdlp.NET.Test/Ytdlp.NET.Test.csproj -c Release